from __future__ import annotations

import subprocess
from pathlib import Path


class MemoryWorkspace:
    def __init__(self, workspace_dir: Path):
        self.root = workspace_dir / ".autocoder" / "memories"
        self.rollout_summaries_dir = self.root / "rollout_summaries"
        self.extensions_notes_dir = self.root / "extensions" / "ad_hoc" / "notes"
        self.skills_dir = self.root / "skills"
        self.diff_file = self.root / "phase2_workspace_diff.md"

    def ensure_initialized(self) -> bool:
        try:
            self.root.mkdir(parents=True, exist_ok=True)
            self.rollout_summaries_dir.mkdir(parents=True, exist_ok=True)
            self.extensions_notes_dir.mkdir(parents=True, exist_ok=True)
            self.skills_dir.mkdir(parents=True, exist_ok=True)

            git_dir = self.root / ".git"
            if not git_dir.exists():
                subprocess.run(["git", "init"], cwd=str(self.root), check=True, capture_output=True)
                subprocess.run(["git", "config", "user.email", "autocoder@local"], cwd=str(self.root), check=True, capture_output=True)
                subprocess.run(["git", "config", "user.name", "AutoCoder Memory"], cwd=str(self.root), check=True, capture_output=True)

                baseline = self.root / ".baseline"
                baseline.write_text("memory workspace baseline\n", encoding="utf-8")
                subprocess.run(["git", "add", "."], cwd=str(self.root), check=True, capture_output=True)
                subprocess.run(["git", "commit", "-m", "init memory workspace"], cwd=str(self.root), check=True, capture_output=True)
                print(f"✅ [Memory] Git workspace initialized at {self.root}")

            self.remove_workspace_diff()
            return True
        except Exception as e:
            print(f"❌ [Memory] Workspace init failed: {e}")
            return False

    def remove_workspace_diff(self) -> None:
        try:
            if self.diff_file.exists():
                self.diff_file.unlink()
        except Exception:
            pass

    def get_diff(self) -> str:
        self.remove_workspace_diff()
        try:
            stat = subprocess.run(
                ["git", "diff", "--stat"],
                cwd=str(self.root),
                capture_output=True,
                text=True,
            )
            full = subprocess.run(
                ["git", "diff"],
                cwd=str(self.root),
                capture_output=True,
                text=True,
            )
            return (stat.stdout or "") + "\n" + (full.stdout or "")
        except Exception:
            return ""

    def has_changes(self) -> bool:
        try:
            res = subprocess.run(
                ["git", "status", "--porcelain"],
                cwd=str(self.root),
                capture_output=True,
                text=True,
            )
            return bool((res.stdout or "").strip())
        except Exception:
            return False

    def write_workspace_diff(self, diff_text: str) -> None:
        rendered = (
            "# Memory Workspace Diff\n\n"
            "Generated before Phase 2 consolidation. Read first; do not edit this file.\n\n"
            "```diff\n"
            f"{diff_text[:4 * 1024 * 1024]}\n"
            "```\n"
        )
        self.diff_file.write_text(rendered, encoding="utf-8")

    def commit_baseline(self, message: str) -> bool:
        self.remove_workspace_diff()
        if not self.has_changes():
            return True
        try:
            subprocess.run(["git", "add", "."], cwd=str(self.root), check=True, capture_output=True)
            subprocess.run(["git", "commit", "-m", message], cwd=str(self.root), check=True, capture_output=True)
            print(f"📌 [Memory] Git committed: {message}")
            return True
        except subprocess.CalledProcessError:
            return False
        except Exception as e:
            print(f"⚠️ [Memory] Git commit failed: {e}")
            return False